name: Update BTC/USD Feature Store

on:
  schedule:
    # Run every hour in EST (November to March, offset by +5)
    - cron: "0 5-23,0-4 * 11-3 *"
    # Run every hour in EDT (March to November, offset by +4)
    - cron: "0 4-23,0-3 * 3-11 *"
  workflow_dispatch: # Allows manual trigger

jobs:
  update_feature_store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure required packages are in this file

      - name: Run Feature Pipeline
        env:
          API_KEY: ${{ secrets.API_KEY }} # Set your BTC/USD API key as a secret
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }} # Set your Hopsworks API key as a secret
        run: |
          python src/feature/pipeline/feature_pipeline.py
